#! /bin/sh

# Depends:
#  python,
#  python-mock,
#  python3,
#  python3 (>= 3.3) | python3-mock,
#  procmail,
#  squashfs-tools,
#  zsync

if [ -z "$*" ]; then
	set -- discover cdimage.tests
fi

PYTHONPATH=lib python -m unittest "$@"
if which python3 >/dev/null 2>&1; then
	PYTHONPATH=lib python3 -m unittest "$@"
fi
