#! /bin/sh

PROJECT="${PROJECT:-ubuntu}"
CAPPROJECT="${CAPPROJECT:-Ubuntu}"
DIST="${DIST:-hoary}"
case $DIST in
	warty|hoary)
		ARCHES="${ARCHES:-amd64 i386 powerpc}"
		;;
	*)
		ARCHES="${ARCHES:-amd64 i386 ia64 powerpc}"
		;;
esac

GNUPG_DIR="$CDIMAGE_ROOT/secret/dot-gnupg"
SIGNING_KEYID=FBB75451

umask 002
