#! /bin/sh

# Settings for building Ubuntu CD images.  The build procedure also involves
# syncing a local Ubuntu mirror; see etc/anonftpsync (or
# production/anonftpsync if it exists) for settings affecting what is
# mirrored and where.

# This will eventually become a more declarative configuration file.  In the
# meantime, do not add new variable settings to this file unless you also
# update lib/cdimage/config.py, or unless their names start with "CDIMAGE_"
# and they are exported to the environment.

export LC_ALL=C

PROJECT="${PROJECT:-ubuntu}"
CAPPROJECT="${CAPPROJECT:-Ubuntu}"
IMAGE_FORMAT=${IMAGE_FORMAT:-iso}
case $PROJECT in
	ubuntu-mid)
		IMAGE_FORMAT=${IMAGE_FORMAT:-vfat}
		;;
esac
export IMAGE_FORMAT
DIST="${DIST:-cosmic}"

case $DIST in
	xenial)
		PROPOSED="${PROPOSED:-1}"
		export PROPOSED
		;;
	bionic)
		PROPOSED="${PROPOSED:-1}"
		export PROPOSED
		;;
esac

# If you want to build image for one or more architectures comment out the
# following line
#ARCHES=i386

# All projects currently being built.  This is used for building source
# images.  Note that we only need to include projects with their own seed
# collections, so not ubuntu-server.

case $DIST in
    precise)
        ALL_PROJECTS="${ALL_PROJECTS:-ubuntu kubuntu edubuntu xubuntu ubuntustudio mythbuntu lubuntu}"
        ;;
    trusty)
        ALL_PROJECTS="${ALL_PROJECTS:-ubuntu kubuntu edubuntu xubuntu ubuntustudio mythbuntu lubuntu ubuntu-gnome ubuntukylin}"
        ;;
    xenial)
        ALL_PROJECTS="${ALL_PROJECTS:-ubuntu kubuntu xubuntu ubuntustudio mythbuntu lubuntu ubuntu-gnome ubuntukylin ubuntu-mate}"
        ;;
    bionic)
        ALL_PROJECTS="${ALL_PROJECTS:-ubuntu kubuntu xubuntu lubuntu ubuntukylin ubuntu-mate ubuntu-budgie}"
        ;;
    *)
        ALL_PROJECTS="${ALL_PROJECTS:-ubuntu kubuntu xubuntu ubuntustudio lubuntu ubuntukylin ubuntu-mate ubuntu-budgie}"
        ;;
esac

GNUPG_DIR="$CDIMAGE_ROOT/secret/dot-gnupg"
SIGNING_KEYID='FBB75451 EFE21092'

#export LOCAL_SEEDS=file:///path/to/local_seeds

# Do not update the local mirror
#export CDIMAGE_NOSYNC=1 

# Do not create source iso
if [ -z "$CDIMAGE_ONLYSOURCE" ]; then
	export CDIMAGE_NOSOURCE=1
fi

# Hosts that need to be notified when the build is done.  Third-party users
# will want to keep this variable empty.
# The "async" mirrors will be notified asynchronously, i.e. we won't wait for
# them to respond.
# If these are unset, the contents of
# $CDIMAGE_ROOT/production/trigger-mirrors will be used if present.
TRIGGER_MIRRORS=
TRIGGER_MIRRORS_ASYNC=

export TRIGGER_MIRRORS
export TRIGGER_MIRRORS_ASYNC

umask 002
